## Muhammad Muzammil
20 September 2024
##### Pandas Practice on Dataset

### **Importing Pandas**

In [1]:
import pandas as pd

Reading Excel File (Prerequisite = Install "openpyxl")

In [3]:
pkfile = pd.read_excel("Dataset_Pandas_Practice.xlsx")
pkfile

,City,Province,Population (millions),Literacy Rate (%),Major Language,Unemployment Rate (%),GDP (billion PKR),Major Industry
0,Quetta,KPK,0.98,99,Sindhi,6.59,8133,Textiles
1,Faisalabad,Balochistan,1.64,68,Saraiki,4.32,2620,Telecom
2,Hyderabad,Sindh,6.26,64,Pashto,6.31,3181,Telecom
3,Islamabad,Balochistan,2.42,72,Sindhi,3.61,1528,Banking
4,Rawalpindi,Punjab,8.73,88,Punjabi,3.23,4067,Healthcare
...,...,...,...,...,...,...,...,...
195,Peshawar,Sindh,0.58,80,Saraiki,5.22,5513,Healthcare
196,Peshawar,Sindh,5.21,88,Balochi,9.54,4766,IT
197,Peshawar,Sindh,5.81,50,Sindhi,11.93,710,Manufacturing
198,Lahore,Sindh,6.24,78,Pashto,3.89,1827,Education
199,Peshawar,Punjab,10.58,63,Pashto,6.61,1954,Banking

### Displays first five rows of dataset

In [4]:
print(pkfile.head())

         City     Province  Population (millions)  Literacy Rate (%)  \
0      Quetta          KPK                   0.98                 99
1  Faisalabad  Balochistan                   1.64                 68
2   Hyderabad        Sindh                   6.26                 64
3   Islamabad  Balochistan                   2.42                 72
4  Rawalpindi       Punjab                   8.73                 88

  Major Language  Unemployment Rate (%)  GDP (billion PKR) Major Industry
0         Sindhi                   6.59               8133       Textiles
1        Saraiki                   4.32               2620        Telecom
2         Pashto                   6.31               3181        Telecom
3         Sindhi                   3.61               1528        Banking
4        Punjabi                   3.23               4067     Healthcare

### Displays Last five rows of dataset

In [5]:
print(pkfile.tail())

         City Province  Population (millions)  Literacy Rate (%)  \
195  Peshawar    Sindh                   0.58                 80
196  Peshawar    Sindh                   5.21                 88
197  Peshawar    Sindh                   5.81                 50
198    Lahore    Sindh                   6.24                 78
199  Peshawar   Punjab                  10.58                 63

    Major Language  Unemployment Rate (%)  GDP (billion PKR) Major Industry
195        Saraiki                   5.22               5513     Healthcare
196        Balochi                   9.54               4766             IT
197         Sindhi                  11.93                710  Manufacturing
198         Pashto                   3.89               1827      Education
199         Pashto                   6.61               1954        Banking

### index and Columns

In [8]:
pkfile.index

RangeIndex(start=0, stop=200, step=1)

In [9]:
pkfile.columns

Index(['City', 'Province', 'Population (millions)', 'Literacy Rate (%)',
       'Major Language', 'Unemployment Rate (%)', 'GDP (billion PKR)',
       'Major Industry'],
      dtype='object')

### **describe()** shows a quick statistic summary of your data:

In [10]:
pkfile.describe()

,Population (millions),Literacy Rate (%),Unemployment Rate (%),GDP (billion PKR)
count,200.000000,200.000000,200.000000,200.000000
mean,7.966100,68.650000,7.417650,4730.215000
std,4.302743,16.797269,2.667878,2918.628403
min,0.570000,40.000000,3.080000,197.000000
25%,3.935000,54.000000,4.940000,2101.000000
50%,8.275000,67.500000,7.470000,4627.500000
75%,11.340000,83.000000,9.662500,7453.250000
max,14.990000,99.000000,11.970000,9979.000000

### Transpose (Rows into columns and Columns into Rows)

In [11]:
pkfile.T

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
City,Quetta,Faisalabad,Hyderabad,Islamabad,Rawalpindi,Lahore,Faisalabad,Lahore,Peshawar,Faisalabad,...,Sialkot,Hyderabad,Lahore,Quetta,Multan,Peshawar,Peshawar,Peshawar,Lahore,Peshawar
Province,KPK,Balochistan,Sindh,Balochistan,Punjab,Sindh,Punjab,Punjab,Sindh,Punjab,...,Balochistan,Punjab,Balochistan,Sindh,Punjab,Sindh,Sindh,Sindh,Sindh,Punjab
Population (millions),0.98,1.64,6.26,2.42,8.73,10.5,12.11,3.4,2.93,2.02,...,12.07,6.82,12.36,2.24,8.4,0.58,5.21,5.81,6.24,10.58
Literacy Rate (%),99,68,64,72,88,71,88,74,83,77,...,57,42,81,93,78,80,88,50,78,63
Major Language,Sindhi,Saraiki,Pashto,Sindhi,Punjabi,Saraiki,Punjabi,English,Hindko,Balochi,...,Saraiki,Urdu,Saraiki,English,Saraiki,Saraiki,Balochi,Sindhi,Pashto,Pashto
Unemployment Rate (%),6.59,4.32,6.31,3.61,3.23,4.22,11.67,7.95,11.69,6.89,...,8.73,9.85,4.44,7.15,3.08,5.22,9.54,11.93,3.89,6.61
GDP (billion PKR),8133,2620,3181,1528,4067,6545,9214,2259,5232,2647,...,197,3850,8635,8274,8203,5513,4766,710,1827,1954
Major Industry,Textiles,Telecom,Telecom,Banking,Healthcare,IT,Agriculture,Banking,IT,Education,...,Banking,Telecom,Telecom,Education,Textiles,Healthcare,IT,Manufacturing,Education,Banking

### Sorting values by ***

In [17]:
pkfile.sort_values(by="City")

,City,Province,Population (millions),Literacy Rate (%),Major Language,Unemployment Rate (%),GDP (billion PKR),Major Industry
99,Faisalabad,KPK,2.40,49,Saraiki,9.64,8099,Manufacturing
34,Faisalabad,KPK,13.14,73,Balochi,7.58,7421,Manufacturing
50,Faisalabad,KPK,1.55,84,Punjabi,9.92,261,Healthcare
178,Faisalabad,Sindh,14.67,71,Sindhi,10.36,7621,Textiles
174,Faisalabad,Balochistan,2.05,54,Punjabi,3.39,3162,IT
...,...,...,...,...,...,...,...,...
167,Sialkot,Balochistan,14.00,72,Saraiki,9.56,8716,Manufacturing
138,Sialkot,Sindh,0.57,47,Hindko,11.82,2743,IT
172,Sialkot,Punjab,6.21,87,Punjabi,11.86,6733,Telecom
32,Sialkot,KPK,4.08,51,Pashto,9.23,1113,Telecom
162,Sialkot,Balochistan,7.71,86,Saraiki,11.27,8200,Textiles

### Displaying only selected Column

In [21]:
pkfile["City"]

0          Quetta
1      Faisalabad
2       Hyderabad
3       Islamabad
4      Rawalpindi
          ...
195      Peshawar
196      Peshawar
197      Peshawar
198        Lahore
199      Peshawar
Name: City, Length: 200, dtype: object

### Slicing the DataFrame

In [24]:
pkfile[0:10]

,City,Province,Population (millions),Literacy Rate (%),Major Language,Unemployment Rate (%),GDP (billion PKR),Major Industry
0,Quetta,KPK,0.98,99,Sindhi,6.59,8133,Textiles
1,Faisalabad,Balochistan,1.64,68,Saraiki,4.32,2620,Telecom
2,Hyderabad,Sindh,6.26,64,Pashto,6.31,3181,Telecom
3,Islamabad,Balochistan,2.42,72,Sindhi,3.61,1528,Banking
4,Rawalpindi,Punjab,8.73,88,Punjabi,3.23,4067,Healthcare
5,Lahore,Sindh,10.50,71,Saraiki,4.22,6545,IT
6,Faisalabad,Punjab,12.11,88,Punjabi,11.67,9214,Agriculture
7,Lahore,Punjab,3.40,74,English,7.95,2259,Banking
8,Peshawar,Sindh,2.93,83,Hindko,11.69,5232,IT
9,Faisalabad,Punjab,2.02,77,Balochi,6.89,2647,Education

### Displaying a specific DataSet

In [27]:
pkfile.loc[150]

City                     Rawalpindi
Province                      Sindh
Population (millions)          3.43
Literacy Rate (%)                99
Major Language               Hindko
Unemployment Rate (%)          6.95
GDP (billion PKR)              9235
Major Industry            Education
Name: 150, dtype: object

### Displaying a specific DataSet with specific Columns

In [33]:
pkfile.loc[0:10, ["City", "Major Language"]]

          City Major Language
0       Quetta         Sindhi
1   Faisalabad        Saraiki
2    Hyderabad         Pashto
3    Islamabad         Sindhi
4   Rawalpindi        Punjabi
5       Lahore        Saraiki
6   Faisalabad        Punjabi
7       Lahore        English
8     Peshawar         Hindko
9   Faisalabad        Balochi
10   Islamabad        Saraiki

### Selection by position

In [36]:
pkfile.iloc[1]

City                      Faisalabad
Province                 Balochistan
Population (millions)           1.64
Literacy Rate (%)                 68
Major Language               Saraiki
Unemployment Rate (%)           4.32
GDP (billion PKR)               2620
Major Industry               Telecom
Name: 1, dtype: object

### Conditions

In [38]:
pkfile[pkfile["GDP (billion PKR)"] > 4]

,City,Province,Population (millions),Literacy Rate (%),Major Language,Unemployment Rate (%),GDP (billion PKR),Major Industry
0,Quetta,KPK,0.98,99,Sindhi,6.59,8133,Textiles
1,Faisalabad,Balochistan,1.64,68,Saraiki,4.32,2620,Telecom
2,Hyderabad,Sindh,6.26,64,Pashto,6.31,3181,Telecom
3,Islamabad,Balochistan,2.42,72,Sindhi,3.61,1528,Banking
4,Rawalpindi,Punjab,8.73,88,Punjabi,3.23,4067,Healthcare
...,...,...,...,...,...,...,...,...
195,Peshawar,Sindh,0.58,80,Saraiki,5.22,5513,Healthcare
196,Peshawar,Sindh,5.21,88,Balochi,9.54,4766,IT
197,Peshawar,Sindh,5.81,50,Sindhi,11.93,710,Manufacturing
198,Lahore,Sindh,6.24,78,Pashto,3.89,1827,Education
199,Peshawar,Punjab,10.58,63,Pashto,6.61,1954,Banking

### Droping any rows that have missing data:

In [44]:
pkfile.dropna(how="any")

,City,Province,Population (millions),Literacy Rate (%),Major Language,Unemployment Rate (%),GDP (billion PKR),Major Industry
0,Quetta,KPK,0.98,99,Sindhi,6.59,8133,Textiles
1,Faisalabad,Balochistan,1.64,68,Saraiki,4.32,2620,Telecom
2,Hyderabad,Sindh,6.26,64,Pashto,6.31,3181,Telecom
3,Islamabad,Balochistan,2.42,72,Sindhi,3.61,1528,Banking
4,Rawalpindi,Punjab,8.73,88,Punjabi,3.23,4067,Healthcare
...,...,...,...,...,...,...,...,...
195,Peshawar,Sindh,0.58,80,Saraiki,5.22,5513,Healthcare
196,Peshawar,Sindh,5.21,88,Balochi,9.54,4766,IT
197,Peshawar,Sindh,5.81,50,Sindhi,11.93,710,Manufacturing
198,Lahore,Sindh,6.24,78,Pashto,3.89,1827,Education
199,Peshawar,Punjab,10.58,63,Pashto,6.61,1954,Banking

### Filling missing data:

In [45]:
pkfile.fillna(value= 00000)

,City,Province,Population (millions),Literacy Rate (%),Major Language,Unemployment Rate (%),GDP (billion PKR),Major Industry
0,Quetta,KPK,0.98,99,Sindhi,6.59,8133,Textiles
1,Faisalabad,Balochistan,1.64,68,Saraiki,4.32,2620,Telecom
2,Hyderabad,Sindh,6.26,64,Pashto,6.31,3181,Telecom
3,Islamabad,Balochistan,2.42,72,Sindhi,3.61,1528,Banking
4,Rawalpindi,Punjab,8.73,88,Punjabi,3.23,4067,Healthcare
...,...,...,...,...,...,...,...,...
195,Peshawar,Sindh,0.58,80,Saraiki,5.22,5513,Healthcare
196,Peshawar,Sindh,5.21,88,Balochi,9.54,4766,IT
197,Peshawar,Sindh,5.81,50,Sindhi,11.93,710,Manufacturing
198,Lahore,Sindh,6.24,78,Pashto,3.89,1827,Education
199,Peshawar,Punjab,10.58,63,Pashto,6.61,1954,Banking

# Operations on Data

### Stats



Mean Value of column

In [49]:
pkfile['Unemployment Rate (%)'].mean()

np.float64(7.41765)

In [51]:
pkfile.value_counts("Unemployment Rate (%)")

Unemployment Rate (%)
4.09     3
9.64     3
7.14     3
8.73     3
4.35     2
        ..
11.85    1
11.86    1
11.93    1
11.95    1
11.97    1
Name: count, Length: 172, dtype: int64